# Generated by Django 3.1.3 on 2020-11-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="base_product",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="substitute",
        ),
    ]
