# Generated by Django 3.1.3 on 2020-11-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('password', models.CharField(max_length=50, verbose_name='Mot de passe')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product', models.ManyToManyField(blank=True, related_name='Produit', to='catalog.Product')),
                ('substitute', models.ManyToManyField(blank=True, related_name='Substitution', to='catalog.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'Favoris',
            },
        ),
    ]
