# Generated by Django 3.1.3 on 2020-11-21 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20201121_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='Favoris', to=settings.AUTH_USER_MODEL),
        ),
    ]
