# Generated by Django 3.1.3 on 2020-11-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201120_0849'),
        ('account', '0002_auto_20201120_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubstitute',
            new_name='Favorite',
        ),
    ]
